---
version: "2.4"
services:
  python-env:
    image: python:3
    tty: true
    environment:
      - PYTHONPATH=/project
    volumes:
      - .:/project
    working_dir: /project
    command: python ./src/main.py
 